
[package]

name = "Hash_Pool"
authors = ["AreaLayer"]
license = "MIT"
description = "A simple library for Mining pools and developers"
documentation = "https://docs.rs/hashpool"
homepage = "https://www.arealayer.net/projects"
version = "1.0.16-beta"
edition = "2021"

[dependencies]

crypto = { version = "0.5.1", features = ["digest"] }
bdk = "=1.0.0-alpha.11"
bdk_electrum = "0.19.0"
bitcoin = "=0.32.3"
lightning = "=0.0.124"
sha2 = "=0.10.8"
ppv-lite86 = "0.2.20"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio-util = "0.7"
futures = "0.3"

[lib]

name = "mining"
path = "src/lib.rs"

# Explicitly include everything needed in the published package
[[bin]]

name = "hashpoold"
path = "bin/hashpoold.rs"
