
[package]

name = "Hash_Pool"
author = "22388o"
license = "MIT"
description = "A simple library for Mining pools and developers"
documentation = "https://docs.rs/hashpool"
version = "1.0.14-beta"

[dependencies]

crypto = { version = "0.5.1", features = ["digest"] }
bdk = "=1.0.0-alpha.11"
bdk_electrum = "0.17.0"
bitcoin = "=0.32.2"
lightning = "=0.0.124"
sha2 = "=0.10.8"
ppv-lite86 = "0.2.20"

[lib]

name = "mining"
path = "src/lib.rs"

[[bin]]

name = "hashpoold"
path = "bin/hashpoold.rs"