
[package]

name = "Hash_Pool"
author = "22388o"
description = "A simple library for Mining pools and developers"
documentation = "https://docs.rs/hashpool"
version = "1.0.10-beta"

[dependencies]
bdk = "1.0.0-alpha.13"
bitcoin = "0.32.0"
lighning = "0.0.123"

[lib]

name = "mining"
path = "src/mining/lib.rs"

name = "on-chain"
path = "src/on-chain/lib.rs"

name "data"
path = "src/data/lib.rs"

[bin]

name = "hashpoold"
path = "bin/hashpoold.rs"