[pcakage]

name = "Hash Pool"
version = "1.0.10-beta"

[package BDK]
bdk = "1.0.0-alpha.13"

[package rust bitcoin]
rust-bitcoin = "0.13.0"

[lightning]
lighning = "0.0.123"

[dependencies]
lihghtning = 
