
[package]

name = "Hash_Pool"
author = "22388o"
license = "MIT"
description = "A simple library for Mining pools and developers"
documentation = "https://docs.rs/hashpool"
version = "1.0.10-beta"

[dependencies]

crypto = "0.5.1"
bdk = "=1.0.0-alpha.11"
bitcoin = "0.32.0"
lightning = "0.0.123"

[lib]

name = "mining"
path = "src/mining/lib.rs"

[[bin]]

name = "hashpoold"
path = "bin/hashpoold.rs"