[package]
name = "mining"
version = "1.0.0"
authors = ["22388o"]
description = "A simple library for Mining pools and developers"
documentation = "https://docs.rs/hashpool"
edition = "2018"

[dependencies]
bdk = "=1.0.0-alpha.11"
bitcoin = "0.32.0"
crypto = "0.5.1"